Feat/tests
Jepria/jfront-ui pull request #30
Opened 2020-09-11 13:53 UTC by Kazeev

//PULL_REQUEST_TEMPLATE.md
Добавил простой рендер всех компонентов(Рендер)
TBD

2020-09-14 10:39 UTC, dmitrii92 requested changes

2020-09-14 10:39 UTC, dmitrii92 commented on packages/checkbox-group/jest.config.js
> +  testEnvironment: "jsdom",
Предлагаю во всех packages использовать jest.config.js из корневого каталога.
А тут использовать так:
const baseConfig = require("../../jest.config")

module.exports = {
  ...baseConfig,
}

2020-09-14 10:39 UTC, dmitrii92 commented on packages/form/tests/form.test.tsx
> +  render(<Form />)
<Form /> и <FormField /> стоит разбить на отдельные тесты

2020-09-14 10:39 UTC, dmitrii92 commented on packages/input/tests/datepicker.test.tsx
> +test("Checking for the existence of an element Input", () => {
Тут думаю тоже надо отдельно по тесту на компонент

2020-09-14 10:39 UTC, dmitrii92 commented on packages/layout/tests/layout.test.tsx
> +test("Checking for the existence of an element Layouts", () => {
И здесь тоже

2020-09-14 11:07 UTC, AlexanderLapygin commented on packages/checkbox-group/jest.config.js
> +  testEnvironment: "jsdom",
Согласен, сам такое делаю.

2020-10-28 14:38 UTC, dmitrii92 approved these changes

2020-10-28 14:38 UTC, merged